"""
app/about_tab.py — Pestaña "About": qué es MIA, cómo funciona, estado experimental y
cómo enviar comentarios.

Los comentarios llegan por las "Issues" del repositorio público (config.REPO_URL):
es el canal habitual de un proyecto abierto y no expone ningún correo personal. El
enlace lleva ya el título y un cuerpo con la información técnica (versión, perfil,
modelos) para que el usuario no tenga que buscarla.
"""

import platform
import sys
import urllib.parse
from pathlib import Path

import streamlit as st

sys.path.append(str(Path(__file__).resolve().parent.parent))
import config


def _diagnostic_block():
    """Texto con la información útil para un informe de fallo (sin datos personales)."""
    return (
        f"MIA version: {config.APP_VERSION}\n"
        f"Active profile: {config.DOMAIN_SLUG} ({config.DISEASE}, {len(config.DRUGS)} drugs)\n"
        f"Embeddings: {config.EMBEDDING_BACKEND} · threshold {config.SIMILARITY_THRESHOLD}\n"
        f"LLM: {config.LLM_MODEL}\n"
        f"Python {platform.python_version()} · {platform.system()} {platform.release()}"
    )


def _issue_url(title, body):
    q = urllib.parse.urlencode({"title": title, "body": body})
    return f"{config.REPO_URL.rstrip('/')}/issues/new?{q}"


def render():
    st.markdown(f"### About MIA · Medical Intelligence Agent  \n"
                f"<span style='opacity:.7'>version {config.APP_VERSION} · experimental</span>",
                unsafe_allow_html=True)

    st.warning(
        "**Experimental and under evaluation.** MIA is a research prototype, not a medical "
        "device. Its answers are drafted by a small local language model from the abstracts "
        "it retrieved and can be incomplete or wrong. Always read the cited sources before "
        "using any figure, and never base a clinical decision on MIA alone.",
        icon=":material/science:")

    c1, c2 = st.columns(2, gap="large")
    with c1:
        st.markdown("#### What it is")
        st.markdown(
            "A **local, sovereign evidence engine** for biomedical literature. You ask a question "
            "in natural language about a disease and its drugs; MIA answers with the exact "
            "source of every statement, and nothing you type ever leaves this computer: the "
            "search, the language model and the database all run locally."
        )
        st.markdown("#### How it works")
        st.markdown(
            "1. **Retrieve.** Your question is embedded with **MedCPT**, a biomedical model "
            "trained by the NCBI on 255 million PubMed query–article pairs, and matched against "
            "your local corpus (abstracts from PubMed and trials, with results, from "
            "ClinicalTrials.gov).\n"
            "2. **Gate.** If the best match is below the evidence threshold, MIA does **not** "
            "answer from memory: it says so, or hands over to the **Scout agent**, which "
            "searches the official sources, imports what it finds and retries.\n"
            "3. **Answer and cite.** A local biomedical LLM (OpenBioLLM 8B, via Ollama) writes "
            "the answer using only the retrieved text. The `[Doc N]` citations are then placed "
            "and validated **deterministically**, sentence by sentence, so no citation can "
            "point to a source that does not exist.\n"
            "4. **Figures.** Numbers in the chart (response rates, adverse-event rates) are "
            "extracted from the abstracts with fixed rules, never generated by the model."
        )
    with c2:
        st.markdown("#### What has been built and measured")
        st.markdown(
            "- A **domain profile** per disease: you can load any pathology from the *Build "
            "corpus* tab, and profiles are remembered on this computer.\n"
            "- **Deterministic citations and figures**: the model drafts, the code attributes.\n"
            "- **Scout agent** with two triggers: weak similarity, or a drug named in the "
            "question that is absent from what was retrieved.\n"
            "- **Exportable evidence report** (HTML, printable to PDF).\n"
            "- Measured on atopic dermatitis: the biomedical embedding ranks the correct "
            "evidence first more often than a generalist one on mechanism-style questions "
            "(hit@1 0.875 vs 0.625), and a neutral judge scored the local biomedical LLM on "
            "par with a generalist of the same size (4.16 vs 4.15 / 5)."
        )
        st.markdown("#### Known limits")
        st.markdown(
            "- Questions must be in **English** (the corpus and the model are).\n"
            "- MIA reads **abstracts and trial records**, not full papers or PDFs.\n"
            "- The evidence threshold was calibrated on atopic dermatitis; it behaved well on "
            "psoriasis and retinoblastoma, but check it on very different domains.\n"
            "- With small corpora, sentence-level citations can be missing when all sources "
            "say the same thing."
        )

    st.divider()
    st.markdown("#### Feedback")
    st.markdown(
        "This is a test phase and your experience matters: what worked, what did not, an "
        "answer that was wrong or a source that did not support it. Comments arrive through "
        "the project's public issue tracker; the technical details below are attached "
        "automatically so you do not have to look them up."
    )
    diag = _diagnostic_block()
    body = ("**What happened**\n\n(describe it here; paste the question if relevant)\n\n"
            "**Details**\n```\n" + diag + "\n```")
    b1, b2, b3 = st.columns(3)
    with b1:
        st.link_button("Report a problem", _issue_url("[bug] ", body),
                       icon=":material/bug_report:", width="stretch")
    with b2:
        st.link_button("Suggest an improvement", _issue_url("[idea] ", body),
                       icon=":material/lightbulb:", width="stretch")
    with b3:
        st.link_button("Project page", config.REPO_URL, icon=":material/code:", width="stretch")
    with st.expander("Diagnostic details that will be attached"):
        st.code(diag, language="text")
    st.caption("No personal data is collected: MIA has no telemetry, no accounts and no "
               "server. What you write in an issue is public on GitHub.")
